CREATE TABLE info_hospitais_2021_01(
	COMP CHAR(100),
    CNES CHAR(100) PRIMARY KEY,
    NOME_ESTABELECIMENTO CHAR(255),
    RAZAO_SOCIAL CHAR(255),
    TP_GESTAO CHAR(10),
    CO_TIPO_UNIDADE CHAR(100),
    DS_TIPO_UNIDADE CHAR(100),
    NATUREZA_JURIDICA CHAR(100),
    DESC_NATUREZA_JURIDICA CHAR(255)
);

INSERT INTO info_hospitais_2021_01 (COMP, CNES, NOME_ESTABELECIMENTO, RAZAO_SOCIAL, TP_GESTAO,
    CO_TIPO_UNIDADE, DS_TIPO_UNIDADE, NATUREZA_JURIDICA, DESC_NATUREZA_JURIDICA)
(SELECT COMP, CNES, NOME_ESTABELECIMENTO, RAZAO_SOCIAL, TP_GESTAO,
    CO_TIPO_UNIDADE, DS_TIPO_UNIDADE, NATUREZA_JURIDICA, DESC_NATUREZA_JURIDICA FROM estabelecimentos_2021_01);

SELECT *
FROM end_contato_hospitais_2021_01