CREATE TABLE leitos_2021_06(
	CNES CHAR(100) PRIMARY KEY,
	LEITOS_EXISTENTES INT,
	LEITOS_SUS INT,
    UTI_TOTAL_EXIST INT,
    UTI_TOTAL_SUS INT,
    UTI_ADULTO_EXIST INT,
    UTI_ADULTO_SUS INT,
    UTI_PEDIATRICO_EXIST INT,
    UTI_PEDIATRICO_SUS INT,
    UTI_NEONATAL_EXIST INT,
    UTI_NEONATAL_SUS INT,
    UTI_QUEIMADO_EXIST INT,
    UTI_QUEIMADO_SUS INT,
    UTI_CORONARIANA_EXIST INT,
    UTI_CORONARIANA_SUS INT
    );

INSERT INTO leitos_2021_06 (CNES, LEITOS_EXISTENTES, LEITOS_SUS, UTI_TOTAL_EXIST, UTI_TOTAL_SUS, UTI_ADULTO_EXIST, UTI_ADULTO_SUS, UTI_PEDIATRICO_EXIST, UTI_PEDIATRICO_SUS, UTI_NEONATAL_EXIST,
UTI_NEONATAL_SUS, UTI_QUEIMADO_EXIST, UTI_QUEIMADO_SUS, UTI_CORONARIANA_EXIST, UTI_CORONARIANA_SUS)
(SELECT CNES, LEITOS_EXISTENTES, LEITOS_SUS, UTI_TOTAL_EXIST, UTI_TOTAL_SUS, UTI_ADULTO_EXIST, UTI_ADULTO_SUS, UTI_PEDIATRICO_EXIST, UTI_PEDIATRICO_SUS, UTI_NEONATAL_EXIST,
UTI_NEONATAL_SUS, UTI_QUEIMADO_EXIST, UTI_QUEIMADO_SUS, UTI_CORONARIANA_EXIST, UTI_CORONARIANA_SUS FROM estabelecimentos_2021_06);
