CREATE TABLE end_contato_hospitais_2021_01(
		CNES CHAR(100) PRIMARY KEY,
	    REGIAO CHAR(100),
		UF CHAR(2),
		MUNICIPIO CHAR(100),
		NO_LOGRADOURO CHAR(255),
		NU_ENDERECO CHAR(100),
		NO_COMPLEMENTO CHAR(255),
		NO_BAIRRO CHAR(100),
		CO_CEP CHAR(100),
		NU_TELEFONE CHAR(150),
		NO_EMAIL CHAR(255)
);

INSERT INTO end_contato_hospitais_2021_01 (CNES, REGIAO, UF, MUNICIPIO, NO_LOGRADOURO, NU_ENDERECO,
		NO_COMPLEMENTO, NO_BAIRRO, CO_CEP, NU_TELEFONE, NO_EMAIL)
(SELECT CNES, REGIAO, UF, MUNICIPIO, NO_LOGRADOURO, NU_ENDERECO,
		NO_COMPLEMENTO, NO_BAIRRO, CO_CEP, NU_TELEFONE, NO_EMAIL FROM estabelecimentos_2021_01);

SELECT *
FROM end_contato_hospitais_2021_01