--Filtrando os dados de disponibilidade de leitos de jan/2021
SELECT *
FROM estabelecimentos_2021
WHERE comp = '202109'

CREATE TABLE estabelecimentos_2021_12(
    COMP CHAR(100),
    REGIAO CHAR(100),
    UF CHAR(2),
    MUNICIPIO CHAR(100),
    MOTIVO_DESABILITACAO CHAR(200),
    CNES CHAR(100) PRIMARY KEY, --CNES é único para cada estabelecimento
    NOME_ESTABELECIMENTO CHAR(255),
    RAZAO_SOCIAL CHAR(255),
    TP_GESTAO CHAR(10),
    CO_TIPO_UNIDADE CHAR(100),
    DS_TIPO_UNIDADE CHAR(100),
    NATUREZA_JURIDICA CHAR(100),
    DESC_NATUREZA_JURIDICA CHAR(255),
    NO_LOGRADOURO CHAR(255),
    NU_ENDERECO CHAR(100),
    NO_COMPLEMENTO CHAR(255),
    NO_BAIRRO CHAR(100),
    CO_CEP CHAR(100),
    NU_TELEFONE CHAR(150),
    NO_EMAIL CHAR(255),
    LEITOS_EXISTENTES INT,
    LEITOS_SUS INT,
    UTI_TOTAL_EXIST INT,
    UTI_TOTAL_SUS INT,
    UTI_ADULTO_EXIST INT,
    UTI_ADULTO_SUS INT,
    UTI_PEDIATRICO_EXIST INT,
    UTI_PEDIATRICO_SUS INT,
    UTI_NEONATAL_EXIST INT,
    UTI_NEONATAL_SUS INT,
    UTI_QUEIMADO_EXIST INT,
    UTI_QUEIMADO_SUS INT,
    UTI_CORONARIANA_EXIST INT,
    UTI_CORONARIANA_SUS INT
);

SELECT *
FROM estabelecimentos_2021_03

CREATE TABLE Hospitais_2021_01(
    COMP CHAR(100),
    CNES CHAR(100),
    NOME_ESTABELECIMENTO CHAR(255),
    RAZAO_SOCIAL CHAR(255),
    CO_TIPO_UNIDADE CHAR(100)
);

INSERT INTO Hospitais_2021_01 (COMP, CNES, NOME_ESTABELECIMENTO, RAZAO_SOCIAL, CO_TIPO_UNIDADE)
(SELECT COMP, CNES, NOME_ESTABELECIMENTO, RAZAO_SOCIAL, CO_TIPO_UNIDADE FROM estabelecimentos_2021_01);

SELECT *
FROM hospitais_2021_01

CREATE TABLE endereços_2021_01(
    UF CHAR(2),
    MUNICIPIO CHAR(100),
    CNES CHAR(100), --CNES é único para cada estabelecimento
    NO_LOGRADOURO CHAR(255),
    NU_ENDERECO CHAR(100),
    NO_COMPLEMENTO CHAR(255),
    NO_BAIRRO CHAR(100),
    CO_CEP CHAR(100)
    );

INSERT INTO endereços_2021_01 (UF, MUNICIPIO, CNES, NO_LOGRADOURO, NU_ENDERECO, NO_COMPLEMENTO, NO_BAIRRO, CO_CEP)
(SELECT UF, MUNICIPIO, CNES, NO_LOGRADOURO, NU_ENDERECO, NO_COMPLEMENTO, NO_BAIRRO, CO_CEP FROM estabelecimentos_2021_01);

SELECT *
FROM endereços_2021_01

CREATE TABLE utis_2021_01(
    CNES CHAR(100), --CNES é único para cada estabelecimento
    UTI_TOTAL_EXIST INT,
    UTI_TOTAL_SUS INT,
    UTI_ADULTO_EXIST INT,
    UTI_ADULTO_SUS INT,
    UTI_PEDIATRICO_EXIST INT,
    UTI_PEDIATRICO_SUS INT,
    UTI_NEONATAL_EXIST INT,
    UTI_NEONATAL_SUS INT,
    UTI_QUEIMADO_EXIST INT,
    UTI_QUEIMADO_SUS INT,
    UTI_CORONARIANA_EXIST INT,
    UTI_CORONARIANA_SUS INT
    );

INSERT INTO utis_2021_01 (CNES, UTI_TOTAL_EXIST, UTI_TOTAL_SUS, UTI_ADULTO_EXIST, UTI_ADULTO_SUS, UTI_PEDIATRICO_EXIST, UTI_PEDIATRICO_SUS, UTI_NEONATAL_EXIST,
UTI_NEONATAL_SUS, UTI_QUEIMADO_EXIST, UTI_QUEIMADO_SUS, UTI_CORONARIANA_EXIST, UTI_CORONARIANA_SUS)
(SELECT CNES, UTI_TOTAL_EXIST, UTI_TOTAL_SUS, UTI_ADULTO_EXIST, UTI_ADULTO_SUS, UTI_PEDIATRICO_EXIST, UTI_PEDIATRICO_SUS, UTI_NEONATAL_EXIST,
UTI_NEONATAL_SUS, UTI_QUEIMADO_EXIST, UTI_QUEIMADO_SUS, UTI_CORONARIANA_EXIST, UTI_CORONARIANA_SUS FROM estabelecimentos_2021_01);

SELECT *
FROM utis_2021_01

CREATE TABLE info_hospitais_2021_01(
    REGIAO CHAR(100),
    MOTIVO_DESABILITACAO CHAR(200),
    CNES CHAR(100), --CNES é único para cada estabelecimento
    TP_GESTAO CHAR(10),
    DS_TIPO_UNIDADE CHAR(100),
    NATUREZA_JURIDICA CHAR(100),
    DESC_NATUREZA_JURIDICA CHAR(255),
    NU_TELEFONE CHAR(150),
    NO_EMAIL CHAR(255)
    );

INSERT INTO info_hospitais_2021_01 (REGIAO, MOTIVO_DESABILITACAO, CNES, TP_GESTAO, DS_TIPO_UNIDADE,
NATUREZA_JURIDICA, DESC_NATUREZA_JURIDICA, NU_TELEFONE, NO_EMAIL)
(SELECT REGIAO, MOTIVO_DESABILITACAO, CNES, TP_GESTAO, DS_TIPO_UNIDADE,
NATUREZA_JURIDICA, DESC_NATUREZA_JURIDICA, NU_TELEFONE, NO_EMAIL FROM estabelecimentos_2021_01);

SELECT *
FROM info_hospitais_2021_01
